### ISSUE TITLE
bug: `get_onsets_offsets` can duplicate the first segment

### ISSUE THREAD

**Issue by NickleDave** [pearsonlab/autoencoded-vocal-analysis#12]
Hi @jackgoffinet @jmxpearson, I think I might have spotted a bug that lets `ava.segmenting.amplitude_segmentation.get_onsets_offsets` duplicate the first segment.

The bug is in this line:
https://github.com/pearsonlab/autoencoded-vocal-analysis/blob/11c95990065ec6bfd3b860b9a9232db3a2f9b89c/ava/segmenting/amplitude_segmentation.py#L78

IIUC, the intention of this line is to skip this local maxima if its index is less than the index of the last offset found.

This works as intended *except* for the first segment found, because of the first part of the conditional, `if len(offsets) > 1`. When the function has found exactly one offset (`len(offsets) == 1`, which is not `> 1`), that part of the conditional allows the code to run through the whole code block for finding the onset and offset. So occasionally the code will duplicate the first segment, because there are two local maxima between the onset and offset, but there's only one offset so far.  

I think what you want is to change the first part of the conditional to `if len(offsets) > 0`.  
I'm happy to make a PR to fix if you agree.

I'm attaching a set of short clips you can use to reproduce the bug.
The clips were produced from [this script](https://github.com/vocalpy/vocalpy/blob/main/tests/scripts/generate_ava_segment_test_data/generate_test_audio_for_ava_segment_from_jourjine_etal_2023.py) using [this tar](https://datadryad.org/stash/downloads/file_stream/2143657) from [this dataset](https://doi.org/10.5061/dryad.g79cnp5ts) (see script for detail).

The parameters you want to use are:
```python
seg_params = {
    'min_freq': 20e3, # minimum frequency
    'max_freq': 125e3, # maximum frequency
    'nperseg': 1024, # FFT
    'noverlap': 1024//2, # FFT
    'spec_min_val': .8, # minimum log-spectrogram value
    'spec_max_val': 6, # maximum log-spectrogram value
    'fs': 250000, # audio samplerate
    'th_1':.3, # segmenting threshold 1
    'th_2':.3, # segmenting threshold 2
    'th_3':.35, # segmenting threshold 3
    'min_dur':0.015, # minimum syllable duration
    'max_dur': 1, # maximum syllable duration
    'min_intersyllable': .004,
    'smoothing_timescale': 0.00025, # amplitude
    'softmax': False, # apply softmax to the frequency bins to calculate
                      # amplitude
    'temperature':0.01, # softmax temperature parameter
    'thresholds_path': None,
    'algorithm': '<function get_onsets_offsets at 0x7f944cc355f0>', # (defined above)
}
```
(originally from [here](https://github.com/nickjourjine/peromyscus-pup-vocal-evolution/blob/main/scripts/Segmenting%20and%20UMAP.ipynb))

This clip in the attached data produces a duplicated first segment: LL_21462x24783_ltr2_pup2_ch4_2600_f_359_278_fr0_p5_2020-02-27_11-45-23-clip.wav
(The other 2 in the zip don't.)

[data-for-ava-bug.zip](https://github.com/pearsonlab/autoencoded-vocal-analysis/files/14465373/data-for-ava-bug.zip)

These files from the original dataset also produce a duplicated first segment. GitHub won't let me attach them since 25 MB max is allowed.
- LL_21462x24783_ltr2_pup4_ch6_1700_m_358_321_fr0_p5_2020-02-27_11-45-23.wav
- LL_21614x21466_ltr1_pup1_ch1_4200_f_344_303_fr0_p9_2019-05-19_07-48-32.wav

edit: realized I didn't include an example of the result I'm getting that would make it clear. 
this is the .txt file with onset/offset times from LL_21462x24783_ltr2_pup2_ch4_2600_f_359_278_fr0_p5_2020-02-27_11-45-23-clip.wav
```
# Onsets/offsets for /home/pimienta/Documents/repos/coding/vocalpy/vocalpy/tests/scripts/generate_ava_segment_test_data/../../../tests/data-for-tests/source/jourjine-et-al-2023/developmentLL/LL_21462x24783_ltr2_pup2_ch4_2600_f_359_278_fr0_p5_2020-02-27_11-45-23-clip.wav
0.53658 0.56115
0.53658 0.56115
1.35578 1.47456
1.59539 1.74899
1.88826 2.09510
2.25280 2.27328
2.50880 2.52518
2.78528 2.80986
3.40173 3.42221
4.26803 4.28442
4.54246 4.55885
4.79437 4.81075
5.00941 5.03194
5.15072 5.30022
5.42310 5.59104
5.74669 5.93715
6.09075 6.11123
6.32627 6.34470
6.34470 6.35699
6.55360 6.57818
6.58022 6.59456
6.79936 6.81779
6.81984 6.83622
7.84384 7.85613
8.80026 8.81869
9.39213 9.40851
9.99629 10.02496
10.55744 10.57792
10.76019 10.84621
10.96499 11.11450
11.28448 11.45651
11.60397 11.62650
11.86202 11.88250
11.88864 11.90093
12.16922 12.18970
12.73651 12.77338
14.63296 14.64730
14.79066 14.80294
14.82547 14.96269
15.07738 15.22893
15.38458 15.43168
15.45626 15.49517
15.63238 15.65491
15.85766 15.88019
15.88224 15.89453
16.12800 16.14234
16.37376 16.39424
16.93901 16.95744
17.56979 17.58618
17.89747 17.91386
18.85184 18.86413
19.40480 19.41914
19.61984 19.75910

```
Notice the first and second onset and offset are the same.

Hope that I've got this right and I'm not just adding noise to the repo! Please let me know if there's any other info you need from me

**Comment by jmxpearson** [comment]
Thank you for this! I’ll let @jackgoffinet take a look to see what he thinks, but I think we’d welcome a PR!

**Comment by jackgoffinet** [comment]
Hey @NickleDave ,

Thanks for pointing this out! That makes a lot of sense and I agree that changing the first part of the conditional to ``if len(offsets) > 0`` would fix the bug. If you're up to provide a PR, I'd be happy to merge it.

Best,

Jack

**Comment by NickleDave** [comment]
Will do!
