### ISSUE TITLE
Variability index

### ISSUE THREAD

**Issue by dlaplagne** [pearsonlab/autoencoded-vocal-analysis#3]
Hello,

I am trying to calculate a running V.I. as in Figure 6e but I am not sure I follow the methods in "Birdsong variability index". Would it be possible to share a piece of code implementing it? 
Even if it does not smoothly integrate with the rest of the package I am sure it would help me better dissect how the index is built.

Thank you!

**Comment by jackgoffinet** [comment]
Hi, yes, here is a file that makes the plots in figure 6c-e. The whole figure is made in `triple_plot_DC` and 6e is made in `warped_variability_plot_DC`. The specific bit of code that computes the variability index is on lines 296-314. This file is a bit rougher than the rest of AVA and was placed in the plotting subdirectory to make these plots.

Best,

Jack

[trace_plot.py.zip](https://github.com/pearsonlab/autoencoded-vocal-analysis/files/9635235/trace_plot.py.zip)

**Comment by dlaplagne** [comment]
Thank you, Jack. I will look into it.

best,
Diego
