### ISSUE TITLE
specs and amps mixed when time warping?

### ISSUE THREAD

**Issue by dlaplagne** [pearsonlab/autoencoded-vocal-analysis#4]
Hello

I believe in this call to _get_specs_and_amplitude_traces the amps and specs are swapped, as that function returns specs first:

https://github.com/pearsonlab/autoencoded-vocal-analysis/blob/fac3b53280bdac95dd9fb5ab8e276fdb90dab1e3/ava/models/window_vae_dataset.py#L560

As a result, it seems when asking to warp on spectrograms it is actually warping on amplitudes and vice versa?

**Comment by jackgoffinet** [comment]
Thanks for catching this! I've swapped the specs and amps on this line so it should have the correct behavior.
