### ISSUE TITLE
Running AVA for motif level shotgun VAE

### ISSUE THREAD

**Issue by harshidapancholi** [pearsonlab/autoencoded-vocal-analysis#9]
Hi there, I am attempting to use the shotgun VAE, especially the warped version. I tried following the example script, but it seems like that needs me to have the seg csv's, spectrograms and projections ready before hand. The step by step tutorial for warped VAE is not present, so I'm a bit lost in trying to figure out how to run everything. 

I am only running this on 100 files, and up to the Bokeh plot, everything works - I'm able to see which spectrograms match the motif. But after that, when I check the specs folder, I only see 3 spectrograms.

Would you happen to have an example for warped shotgun VAE that takes me through the initial preprocessing and segmenting steps as well?

Thank you!

**Comment by jackgoffinet** [comment]
Hi, sorry for my slow response.

For the warped shotgun VAE, the key thing to get right is constructing the [``WarpedWindowDataset``](https://github.com/pearsonlab/autoencoded-vocal-analysis/blob/76a14c7895aebcc773dc30e5a6d8226e32fbbf4a/ava/models/window_vae_dataset.py#L358) object. Each audio file here should only contain the song motif, or the piece of audio you want to subsample. You can construct it by calling the ``get_warped_window_data_loaders`` function.

After constructing the ``WarpedWindowDataset`` object, there are two ways to train the VAE. The first is to use the [``write_hdf5_files``](https://github.com/pearsonlab/autoencoded-vocal-analysis/blob/76a14c7895aebcc773dc30e5a6d8226e32fbbf4a/ava/models/window_vae_dataset.py#L426C6-L426C22) function to write a bunch of warped spectrogram hdf5 files. Then you can train the VAE using a normal syllable dataloader, using each of the random chunks as a syllable. The second option is to pass the warped window dataloader to the VAE directly, which will create spectrograms on the fly during training.

You will also need to write an audio file for each of the song motifs. The "song segmenting" section [here](https://autoencoded-vocal-analysis.readthedocs.io/en/latest/segment.html) might be useful, depending on how stereotyped the motifs are.

Let me know if you run into any other issues or have more questions.

Best,

Jack
